networks:
  dev:

services:

  api:
    image: my-spring-boot-app
    build: ./api
    ports:
      - '9090:9090'
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_API_URL: http://185.91.54.108:5173
    expose:
      - 9090
    networks:
      - dev 
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      DB_USER: dbUser
      DB_PASSWORD: dbPassword
      DB_NAME: dbDbName
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - dev 

  pgadmin:
    container_name: pg-admin
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: adming@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '80:80'
    expose:
      - 80
    networks:
      - dev 
      
  ui:
    build: ./ui
    container_name: react-ui
    ports:
      - '5173:5173'
    volumes:
      - ./ui:/app
      - /app/node_modules
    expose:
      - 5173
    stdin_open: true
    tty: true
    environment:
      VITE_API_URL: http://localhost:9090
    networks:
      - dev 

