networks:
  dev:
    driver: bridge

services:
  api:
    image: my-spring-boot-app
    build: ./api
    ports:
      - '9090:9090'
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_API_URL: http://185.91.54.108:5173
    expose:
      - 9090
    networks:
      - dev 
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
      DB_USER: dbUser
      DB_PASSWORD: dbPassword
      DB_NAME: dbDbName
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      retries: 5
    networks:
      - dev 

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: adming@admin.com
      PGADMIN_DEFAULT_PASSWORD: oot
    ports:
      - '80:80'
    networks:
      - dev
      
  ui:
    build: ./ui
    container_name: react-ui
    ports:
      - '5173:5173'
    volumes:
      - ./ui:/app
      - /app/node_modules
    expose:
      - 5173
    stdin_open: true
    tty: true
    environment:
      VITE_API_URL: http://185.91.54.108:9090
    networks:
      - dev 
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    networks:
      - dev

