services:
  api:
    image: my-spring-boot-app
    build: ./api
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  ui:
    build: ./ui
    container_name: react-ui
    ports:
      - '5173:5173'
    volumes:
      - ./ui:/app
      - /app/node_modules
    expose:
      - 5173
    stdin_open: true
    tty: true